added role entity and roleRepositiry, implemented springSecurity and used PreAuthorized anotation in bookController
dima-semeniuk/book-store pull request #11
Opened 2023-12-20 13:10 UTC by dima-semeniuk

2023-12-20 20:00 UTC, annton-shakur approved these changes
Great job!

2023-12-21 08:25 UTC, bhdnchui requested changes
Great job! Just one point to consider.

2023-12-21 08:25 UTC, bhdnchui commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
Add an empty line

2023-12-21 08:25 UTC, bhdnchui commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                    references: roles(id)
Add
```
                    deleteCascade: true
                    primaryKey: true
```

2023-12-22 07:33 UTC, bhdnchui approved these changes
LGTM

2023-12-22 11:47 UTC, merged