Implemented JWT support and added login endpoint
dima-semeniuk/book-store pull request #12
Opened 2023-12-21 16:06 UTC by dima-semeniuk

2023-12-22 07:13 UTC, bhdnchui requested changes
A few minor points to consider.

2023-12-22 07:13 UTC, bhdnchui commented on src/main/java/mate/academy/webapp/security/JwtUtil.java
> +    public boolean isValidToken(String token) {
Please, rename. For example `isTokenValid`

2023-12-22 07:13 UTC, bhdnchui commented on src/main/java/mate/academy/webapp/dto/user/UserLoginRequestDto.java
> +
```suggestion
```

2023-12-22 07:13 UTC, bhdnchui commented on src/main/java/mate/academy/webapp/config/SecurityConfig.java
>  package mate.academy.webapp.config;
It's better to place this file in a `security` package.

2023-12-26 09:45 UTC, d1sam approved these changes
Well done!

2023-12-26 09:45 UTC, d1sam commented on src/main/java/mate/academy/webapp/controller/BookController.java
why did you remove `hasRole('ADMIN')`?

2023-12-26 10:44 UTC, merged