Implemented order and orderItem models with its service and controller
dima-semeniuk/book-store pull request #15
Opened 2024-01-03 20:41 UTC by dima-semeniuk

2024-01-03 23:33 UTC, BolsunovaNataliia approved these changes

2024-01-03 23:33 UTC, BolsunovaNataliia commented on src/main/java/mate/academy/webapp/controller/OrderController.java
> +package mate.academy.webapp.controller;
Great job! But I have few notes.

2024-01-03 23:33 UTC, BolsunovaNataliia commented on src/main/java/mate/academy/webapp/controller/OrderController.java
> +        return orderService.getAll(user, pageable);
You can transfer only user.getId()

2024-01-04 09:30 UTC, d1sam requested changes
good job, but one minor change should be done!

2024-01-04 13:23 UTC, vovasalyha approved these changes

2024-01-04 13:25 UTC, merged