Added custom globalException handler and validation for CreateBookReq…
dima-semeniuk/book-store pull request #5
Opened 2023-12-09 13:07 UTC by dima-semeniuk

…uestDto class

2023-12-09 16:12 UTC, RostyslavKuzmych approved these changes
Everything is nice!

2023-12-11 17:02 UTC, bhdnchui requested changes
Just a few minor points to consider.

2023-12-11 17:02 UTC, bhdnchui commented on src/main/java/mate/academy/webapp/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleCustomsException(Exception ex) {
```suggestion
    protected ResponseEntity<Object> handleEntityNotFoundException(Exception ex) {
```

2023-12-12 10:33 UTC, d1sam requested changes
Good job, but some changes should be done, please look at my comments.

2023-12-12 10:33 UTC, d1sam commented on src/main/java/mate/academy/webapp/dto/CreateBookRequestDto.java
> +    @NotNull(message = "can't be null.")
```suggestion
    @NotNull(message = "Title can't be null.")
```

2023-12-12 10:33 UTC, d1sam commented on src/main/java/mate/academy/webapp/dto/CreateBookRequestDto.java
> +    @NotNull(message = "can't be null.")
```suggestion
    @NotNull(message = "Author can't be null.")
```

2023-12-12 10:33 UTC, d1sam commented on src/main/java/mate/academy/webapp/dto/CreateBookRequestDto.java
> +    @NotNull(message = "can't be null.")
```suggestion
    @NotNull(message = "ISBN can't be null.")
```

2023-12-12 10:33 UTC, d1sam commented on src/main/java/mate/academy/webapp/dto/CreateBookRequestDto.java
> +    @NotNull(message = "can't be null.")
```suggestion
    @NotNull(message = "Price can't be null.")
```

2023-12-12 10:33 UTC, d1sam commented on src/main/java/mate/academy/webapp/exception/CustomGlobalExceptionHandler.java
avoid string literals

2023-12-13 06:38 UTC, kshuryhin approved these changes
Looks good

2023-12-13 06:42 UTC, merged