Add Pagination, Sorting, and Swagger
dima-semeniuk/book-store pull request #8
Opened 2023-12-12 09:18 UTC by dima-semeniuk

2023-12-12 11:47 UTC, MinoDentori approved these changes
Well done!

2023-12-13 06:41 UTC, kshuryhin requested changes
Good job, just some clarification regarding DTO validation

2023-12-13 06:41 UTC, kshuryhin commented on src/main/java/mate/academy/webapp/dto/book/CreateBookRequestDto.java
> +    @NotNull(message = "can't be null.")
it looks like these changes are being done in the scope of another PR, aren't they?

2023-12-13 07:02 UTC, kshuryhin requested changes

2023-12-13 07:02 UTC, kshuryhin commented on src/main/java/mate/academy/webapp/dto/book/CreateBookRequestDto.java
> +    @Positive(message = GREATER_THAN_ZERO)
That's a bit confusing, you already have these changes in the main branched, haven't you?

2023-12-13 09:31 UTC, kshuryhin approved these changes
looks good

2023-12-13 09:32 UTC, merged